const data = {
    products: [
        {
            _id: '1',
            name: 'Nokia X20',
            category: 'Smartphone',
            image: '/images/p1.jpg',
            price: 389,
            countInStock: 10,
            brand: 'Nokia',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Nokia X10',
            category: 'Smartphone',
            image: '/images/p2.jpg',
            price: 349,
            countInStock: 0,
            brand: 'Nokia',
            rating: 4,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Nokia G20',
            category: 'Smartphone',
            image: '/images/p3.jpg',
            price: 179,
            countInStock: 0,
            brand: 'Nokia',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nokia G10',
            category: 'Smartphone',
            image: '/images/p4.jpg',
            price: 149,
            countInStock: 15,
            brand: 'Nokia',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nokia C20',
            category: 'Smartphone',
            image: '/images/p5.jpg',
            price: 99,
            countInStock: 5,
            brand: 'Nokia',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nokia 8.3 5G',
            category: 'Smartphone',
            image: '/images/p6.jpg',
            price: 649,
            countInStock: 12,
            brand: 'Nokia',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
};

export default data;